### ISSUE TITLE
!roles doesn't accept role names longer than one word

### ISSUE THREAD

**Issue by Dthen** [Dthen/CubeBox#18]
![image](https://user-images.githubusercontent.com/65791582/101402713-072ff780-38cc-11eb-9f96-73b34c72e011.png)

**Comment by davidwarrington** [comment]
https://github.com/Dthen/CubeBox/blob/master/commands/listroles.js#L8

I think this is the problematic code.
```js
args[0].toLowerCase()
```

If the command doesn't support any extra arguments, you should be able to replace `args[0]` with `args.join(' ')`. `args[0]` is used twice in the module though, so you should probably assign it to a variable.

**Comment by Dthen** [comment]
That looks like it should fix it, let's implent that on Sunday.

**Comment by Dthen** [comment]
What variable would it make sense to assign it to?
it's already assigning the role object to an object which has a name property. I'll need to change it there, but I'm missing what defining a variable would add.

**Comment by Dthen** [comment]
Oh I pushed a commit but that there may be an off-by-one error admist others.
